[SDPA-5674] Refactor Tide Site Preview Link Builder
dpc-sdp/tide_site pull request #96
Opened 2021-11-26 03:49 UTC by FleetAdmiralButter

2021-11-29 02:27 UTC, vincent-gao approved these changes

2021-11-29 02:53 UTC, anthony-malkoun requested changes
Ming, this is 👍 and heaps better than trying to use reflection. Is it possible to have a unit test for the class?

2021-11-29 02:53 UTC, anthony-malkoun commented on modules/tide_site_preview/src/TideSitePreviewHelper.php
> +<?php
Moving this out to a helper class instead of the block class is 💯 .

2021-11-29 02:53 UTC, anthony-malkoun commented on modules/tide_site_preview/src/Plugin/Block/PreviewLinksBlock.php
> +      $container->get('tide_site_preview.helper')
Dependency injection FTW

2021-12-01 04:23 UTC, anthony-malkoun approved these changes

2021-12-01 04:42 UTC, merged